const products = [
  {
    sku:"hi",
    category: "Mugs",
    title: "Black Printed Coffee Mug",
    price: "15.00",
    image: "https://dummyimage.com/300x300/000/fff&text=Black+Mug",
  },
  {
    sku:"hello",
    category: "Mugs",
    title: "Father’s Day Coffee Mug",
    price: "19.00",
    image: "https://dummyimage.com/300x300/111/fff&text=Father's+Mug",
  },
  {
    sku:"codeyogi",
    category: "Tshirts",
    title: "Green Printed Tshirt",
    price: "34.00",
    image: "https://dummyimage.com/300x300/6bf/fff&text=Thankful",
  },
  {
    sku:"apna mug",
    category: "Mugs",
    title: "Personalised Mug",
    price: "15.00",
    image: "https://dummyimage.com/300x300/222/fff&text=Personalized",
  },
  {
    sku:"apni t-shirt",
    category: "Tshirts",
    title: "Printed Brown Tshirt",
    price: "25.00",
    originalPrice: "34.00",
    image: "https://dummyimage.com/300x300/f4a261/fff&text=Brown",
    sale: true,
  },
  {
    sku:"teri t-shirt",
    category: "Tshirts",
    title: "Printed Dark Blue Tshirt",
    price: "34.00",
    image: "https://dummyimage.com/300x300/264653/fff&text=Dark+Blue",
  },
  {
    sku:"sabki t-shirt",
    category: "Tshirts",
    title: "Printed Green Tshirt",
    price: "28.00",
    originalPrice: "35.00",
    image: "https://dummyimage.com/300x300/2a9d8f/fff&text=Green",
    sale: true,
  },
  {
    sku:"ghrwalon ki t-shirt",
    category: "Tshirts",
    title: "Printed Tshirt Coffee Black Color",
    price: "25.00",
    originalPrice: "35.00",
    image: "https://dummyimage.com/300x300/c2185b/fff&text=Coffee",
    sale: true,
  },
  {
    sku:"bharwalon ki t-shirt",
    category: "Tshirts",
    title: "Typography Teal Printed Tshirt",
    price: "22.00",
    originalPrice: "30.00",
    image: "https://dummyimage.com/300x300/e76f51/fff&text=Teal",
    sale: true,
  },
];

export default products;